/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patients;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Patient;
import model.EncounterHistory;
import model.Encounter;
import model.VitalSigns;

/**
 *
 * @author gaurav
 */
public class AddVitalSignsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVitalSignsJPanel
     */
    JPanel userProcessContainer;
    Patient patient;
    EncounterHistory encounterHistory;
    Encounter encounter;
    VitalSigns vitalSigns;

    public AddVitalSignsJPanel(JPanel userProcessContainer, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        txtPatientName.setText(patient.getPerson().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblBodyTemperature = new javax.swing.JLabel();
        lblPulseRate = new javax.swing.JLabel();
        lblRespirationRate = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblGlucoseLevel = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        txtBodyTemperature = new javax.swing.JTextField();
        txtPulseRate = new javax.swing.JTextField();
        txtRespirationRate = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtGlucoseLevel = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtComplaint = new javax.swing.JTextField();

        jLabel1.setText(" Add Vital Signs For Patient :");

        lblBodyTemperature.setText("Body Temperature :");

        lblPulseRate.setText("Pulse Rate :");

        lblRespirationRate.setText("Respiration Rate :");

        lblBloodPressure.setText("Blood Pressure :");

        lblHeight.setText("Height :");

        lblGlucoseLevel.setText("Glucose Level :");

        lblWeight.setText("Weight :");

        jButton1.setText("Add Vitals");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Chief Complaint :");

        txtComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplaintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPulseRate)
                            .addComponent(lblBodyTemperature)
                            .addComponent(lblRespirationRate)
                            .addComponent(lblBloodPressure)
                            .addComponent(lblHeight)
                            .addComponent(lblGlucoseLevel)
                            .addComponent(jLabel2)
                            .addComponent(lblWeight))
                        .addGap(239, 239, 239)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBodyTemperature, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(txtPulseRate)
                            .addComponent(txtRespirationRate)
                            .addComponent(txtComplaint)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(jButton1)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBodyTemperature)
                    .addComponent(txtBodyTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPulseRate)
                    .addComponent(txtPulseRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespirationRate)
                    .addComponent(txtRespirationRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGlucoseLevel)
                    .addComponent(txtGlucoseLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWeight)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtComplaint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(97, 97, 97))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try {

            double bloodPressure = 0;
            double bodyTemperature = 0;
            double glucoseLevel = 0;
            double height = 0;
            double pulseRate = 0;
            double respirationRate = 0;
            double weight = 0;

            try {
                bloodPressure = Double.parseDouble(txtBloodPressure.getText());
                bodyTemperature = Double.parseDouble(txtBodyTemperature.getText());
                glucoseLevel = Double.parseDouble(txtGlucoseLevel.getText());
                height = Double.parseDouble(txtHeight.getText());
                pulseRate = Double.parseDouble(txtPulseRate.getText());
                respirationRate = Double.parseDouble(txtRespirationRate.getText());
                weight = Double.parseDouble(txtWeight.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please provide correct values "
                        + "for bodyTemperature, pulseRate, respirationRate, bloodPressure, "
                        + "height, glucoseLevel, weight");
            }

            if (bloodPressure < 110 || bloodPressure > 150) {
                JOptionPane.showMessageDialog(this, "Blood Pressure should not be less than 110 and not more than 150.");
                return;
            }

            if (bodyTemperature < 97 || bodyTemperature > 100) {
                JOptionPane.showMessageDialog(this, "Body Temperature should not be less than 97 and not more than 100 F1.");
                return;
            }

            if (glucoseLevel < 120 || glucoseLevel > 220) {
                JOptionPane.showMessageDialog(this, "Glucose Level should not be less than 120 and not more than 220.");
                return;
            }

            if (height < 1 || height > 8) {
                JOptionPane.showMessageDialog(this, "Height should not be less than 1 and not more than 8 ft.");
                return;
            }

            if (pulseRate < 50 || pulseRate > 110) {
                JOptionPane.showMessageDialog(this, "Pulse Rate should not be less than 50 and not more than 110.");
                return;
            }

            if (respirationRate < 10 || respirationRate > 20) {
                JOptionPane.showMessageDialog(this, "Respiration Rate should not be less than 10 and not more than 20.");
                return;
            }

            if (weight < 1 || weight > 300) {
                JOptionPane.showMessageDialog(this, "Weight should not be less than 1 and not more than 300 lbs.");
                return;
            }

            patient.setChiefComplaint(txtComplaint.getText());
            vitalSigns = new VitalSigns();
            encounterHistory = patient.getEncounterHistory();
            encounter = encounterHistory.addNewEncounter();
            vitalSigns.setBloodPressure(bloodPressure);
            vitalSigns.setBodyTemperature(bodyTemperature);
            vitalSigns.setGlucoseLevel(glucoseLevel);
            vitalSigns.setHeight(height);
            vitalSigns.setPulseRate(pulseRate);
            vitalSigns.setRespirationRate(respirationRate);
            vitalSigns.setWeight(weight);
            encounter.setVitalSigns(vitalSigns);

            JOptionPane.showMessageDialog(this, "Vital Signs Are Added.");

        } catch (NumberFormatException ex) {
            Logger.getLogger(ViewPatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplaintActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblBodyTemperature;
    private javax.swing.JLabel lblGlucoseLevel;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblPulseRate;
    private javax.swing.JLabel lblRespirationRate;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtBodyTemperature;
    private javax.swing.JTextField txtComplaint;
    private javax.swing.JTextField txtGlucoseLevel;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPulseRate;
    private javax.swing.JTextField txtRespirationRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
