/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patients;

import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Patient;
import model.PatientDirectory;
import model.Encounter;
import model.VitalSigns;

/**
 *
 * @author gaurav
 */
public class OverviewPageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverviewPageJPanel
     */
    JPanel userProcessContainer;
    PatientDirectory pd;
    Patient patient;
    ArrayList<Patient> pL;

    public OverviewPageJPanel(JPanel userProcessContainer, PatientDirectory pd) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pd = pd;
        refreshTableBloodPressure();
        refreshTableGlucoseLevel();
        refreshTablePulseRate();

    }

    public void refreshTableBloodPressure() {
        pL = pd.getPatientList();
        DefaultTableModel model = (DefaultTableModel) tblBloodPressure.getModel();
        model.setRowCount(0);

        int id = 1;
        for (Patient p : pL) {

            for (Encounter e : p.getEncounterHistory().getEncounterHistory()) {
                if(e.getVitalSigns().getBloodPressure()< 130){
                Object row[] = new Object[5];
                row[0] = id;
                row[1] = p.getPatientNo();
                row[2] = e.getVitalSigns().getBloodPressure();
                row[3] = p.getPerson().getHouse().getCommunity().getCommunityName();
                row[4] = p.getPerson().getHouse().getCity().getcityName();
                model.addRow(row);
                id++;
                }
            }
        }
    }

    public void refreshTableGlucoseLevel() {
        pL = pd.getPatientList();
        DefaultTableModel model = (DefaultTableModel) tblGlucoseLevel.getModel();
        model.setRowCount(0);

        int id = 1;
        for (Patient p : pL) {

            for (Encounter e : p.getEncounterHistory().getEncounterHistory()) {
                if(e.getVitalSigns().getGlucoseLevel() < 140){
                Object row[] = new Object[5];
                row[0] = id;
                row[1] = p.getPatientNo();
                row[2] = e.getVitalSigns().getGlucoseLevel();
                row[3] = p.getPerson().getHouse().getCommunity().getCommunityName();
                row[4] = p.getPerson().getHouse().getCity().getcityName();
                model.addRow(row);
                id++;
                }
            }
        }
    }

    public void refreshTablePulseRate() {
        pL = pd.getPatientList();
        DefaultTableModel model = (DefaultTableModel) tblPulseRate.getModel();
        model.setRowCount(0);

        int id = 1;
        for (Patient p : pL) {

            for (Encounter e : p.getEncounterHistory().getEncounterHistory()) {
                if(e.getVitalSigns().getPulseRate()< 70){
                Object row[] = new Object[5];
                row[0] = id;
                row[1] = p.getPatientNo();
                row[2] = e.getVitalSigns().getPulseRate();
                row[3] = p.getPerson().getHouse().getCommunity().getCommunityName();
                row[4] = p.getPerson().getHouse().getCity().getcityName();
                model.addRow(row);
                id++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGlucoseLevel = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBloodPressure = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblPulseRate = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("<<Patient With Blood Pressure Below 130 ");

        jLabel2.setText("<<Patient With Glucose Level Below 140 ");

        jLabel3.setText("Patient With Pulse Rate Below 70 >> ");

        tblGlucoseLevel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Patient Id", "Glucose Level", "Community", "City"
            }
        ));
        jScrollPane2.setViewportView(tblGlucoseLevel);

        tblBloodPressure.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Patient Id", "Blood Pressure", "Community", "City"
            }
        ));
        jScrollPane3.setViewportView(tblBloodPressure);

        tblPulseRate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Patient Id", "Pulse Rate", "Community", "City"
            }
        ));
        jScrollPane4.setViewportView(tblPulseRate);

        jLabel4.setText("Patients With Abnormal Vital Signs");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 34, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(19, 19, 19))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(299, 299, 299))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1)))
                .addGap(0, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(123, 123, 123)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblBloodPressure;
    private javax.swing.JTable tblGlucoseLevel;
    private javax.swing.JTable tblPulseRate;
    // End of variables declaration//GEN-END:variables
}
