/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patients;

import java.awt.CardLayout;
import java.awt.HeadlessException;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.Encounter;
import model.EncounterHistory;
import model.Patient;
import model.VitalSigns;

/**
 *
 * @author gaurav
 */
public class ViewPatientDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientDetailsJPanel
     */
    JPanel userProcessContainer;
    Patient patient;
    EncounterHistory encounterHistory;
    Encounter encounter;
    VitalSigns vitalSigns;

    public ViewPatientDetailsJPanel(JPanel userProcessContainer, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.patient = patient;
        refreshTable();
        ImageIcon ic = new ImageIcon(patient.getPhoto().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        btnBack.setIcon(ic);

        txtAge.setText(String.valueOf(patient.getPerson().getAge()));
        txtChiefComplaint.setText(String.valueOf(patient.getChiefComplaint()));
        txtGender.setText(String.valueOf(patient.getPerson().getGender()));
        txtPatientName.setText(String.valueOf(patient.getPerson().getName()));
        txtPhone.setText(String.valueOf(patient.getPerson().getPhoneNumber()));
    }

    public void refreshTable() {
        encounterHistory = patient.getEncounterHistory();
        
        
        
        DefaultTableModel model = (DefaultTableModel) vitalTable.getModel();
        model.setRowCount(0);
        int id = 1;
        for (Encounter e : encounterHistory.getEncounterHistory()) {
            
            String collectionDate = e.getCollectionDate().toString().substring(4,10) 
                        + "," + e.getCollectionDate().toString().substring(24); 
            
            
            Object row[] = new Object[9];
            row[0] = id;
            row[1] = e;
            row[2] = e.getVitalSigns().getPulseRate();
            row[3] = e.getVitalSigns().getRespirationRate();
            row[4] = e.getVitalSigns().getBloodPressure();
            row[5] = e.getVitalSigns().getHeight();
            row[6] = e.getVitalSigns().getGlucoseLevel();
            row[7] = e.getVitalSigns().getWeight();
            row[8] = collectionDate;
            
           
            
            
            model.addRow(row);
            id++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        vitalTable = new javax.swing.JTable();
        btnBack = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtChiefComplaint = new javax.swing.JTextField();
        btnDeleteVitals = new javax.swing.JButton();
        btnUpdateDetails = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vitalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "S.No.", "Body Temperature", "Pulse Rate", "Respiration Rate", "Blood Pressure", "Height", "Glucose Level", "Weight", "Record Date"
            }
        ));
        jScrollPane1.setViewportView(vitalTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 792, 312));
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, 100));

        jLabel1.setText("Patient Name :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 32, -1, -1));

        jLabel2.setText("Age :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 58, -1, -1));

        jLabel3.setText("Gender :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 84, -1, -1));

        jLabel4.setText("Phone :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 110, -1, -1));

        jLabel5.setText("Chief Complaint :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 136, -1, -1));
        add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 27, 141, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 53, 141, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 79, 141, -1));

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 105, 141, -1));

        txtChiefComplaint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtChiefComplaintActionPerformed(evt);
            }
        });
        add(txtChiefComplaint, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 131, 180, -1));

        btnDeleteVitals.setText("Delete Vitals");
        btnDeleteVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVitalsActionPerformed(evt);
            }
        });
        add(btnDeleteVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 533, -1, -1));

        btnUpdateDetails.setText("Update Details");
        btnUpdateDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDetailsActionPerformed(evt);
            }
        });
        add(btnUpdateDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 533, -1, -1));

        jButton1.setText("<< Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void txtChiefComplaintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtChiefComplaintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtChiefComplaintActionPerformed

    private void btnDeleteVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVitalsActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = vitalTable.getSelectedRow();

        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

//        DefaultTableModel model = (DefaultTableModel) vitalTable.getModel();
        Encounter e = (Encounter) vitalTable.getValueAt(selectedRowIndex, 1);
        encounterHistory.removeEncounter(e);
        JOptionPane.showMessageDialog(null, "Selected Row is deleted", "Info", JOptionPane.INFORMATION_MESSAGE);
        refreshTable();
    }//GEN-LAST:event_btnDeleteVitalsActionPerformed

    private void btnUpdateDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDetailsActionPerformed
        // TODO add your handling code here:
        try {

            int selectedRowIndex = vitalTable.getSelectedRow();

            if (selectedRowIndex < 0) {
                JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
//            DefaultTableModel model = (DefaultTableModel) vitalTable.getModel();
            Encounter e = (Encounter) vitalTable.getValueAt(selectedRowIndex, 1);

            if (e != null) {
                UpdatePatientDetailsJPanel updjp = new UpdatePatientDetailsJPanel(userProcessContainer, e ,patient);
                userProcessContainer.add("UpdatePatientDetailsJPanel", updjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            } else {
                JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
                //return;
            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnUpdateDetailsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnBack;
    private javax.swing.JButton btnDeleteVitals;
    private javax.swing.JButton btnUpdateDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtChiefComplaint;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTable vitalTable;
    // End of variables declaration//GEN-END:variables
}
