/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Patients;

import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.CityDirectory;
import model.Patient;
import model.PatientDirectory;

/**
 *
 * @author gaurav
 */
public class ViewPatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatientJPanel
     */
    
    JPanel userProcessContainer;
    PatientDirectory pd;
    CityDirectory cityList;
    
    public ViewPatientJPanel(JPanel userProcessContainer , PatientDirectory pd, CityDirectory cityList) {
       
        this.userProcessContainer = userProcessContainer;
        this.pd = pd;
        this.cityList = cityList;
        
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnViewSymptoms = new javax.swing.JButton();
        btnViewVitalSigns = new javax.swing.JButton();
        lblPhoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        txtApartmentNo = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        lblPinCode = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        txtPinCode = new javax.swing.JTextField();
        btnSearchPatient = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lblPatientID = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 60, 100, -1));

        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 100, -1));
        jPanel1.add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 100, -1));
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, 100, -1));

        jLabel1.setText("Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel2.setText("Age :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, -1));

        jLabel3.setText("Phone :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        btnViewSymptoms.setText("View Details");
        btnViewSymptoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSymptomsActionPerformed(evt);
            }
        });

        btnViewVitalSigns.setText("Add Details");
        btnViewVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalSignsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnViewVitalSigns)
                .addGap(64, 64, 64)
                .addComponent(btnViewSymptoms)
                .addGap(108, 108, 108)
                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 72, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnViewVitalSigns)
                            .addComponent(btnViewSymptoms)))
                    .addComponent(lblPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 436, -1, -1));

        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));

        jLabel8.setText("Appartment No :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, -1, -1));

        jLabel9.setText("Street :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        lblCity.setText("City :");
        jPanel1.add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));
        jPanel1.add(txtApartmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 100, -1));
        jPanel1.add(txtStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 100, -1));
        jPanel1.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 100, -1));

        lblCommunity.setText("Community :");
        jPanel1.add(lblCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        lblPinCode.setText("PinCode :");
        jPanel1.add(lblPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));
        jPanel1.add(txtCommunity, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 100, -1));
        jPanel1.add(txtPinCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, 100, -1));

        btnSearchPatient.setText("Search Patient");
        btnSearchPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchPatientActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearchPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        jButton1.setText(" << Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblPatientID.setText("Patient ID :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 123, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblPatientID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(266, 266, 266))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientID)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed

    private void btnSearchPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchPatientActionPerformed
        // TODO add your handling code here:

        int patientID = 0;
        try {
               patientID = Integer.parseInt(txtPatientID.getText());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please provide correct value "
                        + "for Patient Id");
                return;
            }
        
        
        Patient p = pd.getPatientById(patientID);
        if(p == null){            
            JOptionPane.showMessageDialog(null, "Please select a correct Patient First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  
        }

        
        txtAge.setText(String.valueOf(p.getPerson().getAge()));
        txtGender.setText(p.getPerson().getGender());
        txtName.setText(p.getPerson().getName());
        txtApartmentNo.setText(String.valueOf(p.getPerson().getHouse().getAppartmentNo()));
        txtCity.setText(p.getPerson().getHouse().getCityName());
        txtCommunity.setText(p.getPerson().getHouse().getCommunity().getCommunityName());
        txtPhone.setText(String.valueOf(p.getPerson().getPhoneNumber()));
        txtPinCode.setText(String.valueOf(p.getPerson().getHouse().getCommunity().getPinCode()));
        txtStreet.setText(p.getPerson().getHouse().getStreet());
        ImageIcon ic = new ImageIcon(p.getPhoto().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        lblPhoto.setIcon(ic);
    }//GEN-LAST:event_btnSearchPatientActionPerformed

    private void btnViewVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalSignsActionPerformed
        // TODO add your handling code here:
        
        int patientID = 0;
        try {
               patientID = Integer.parseInt(txtPatientID.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please provide correct value "
                        + "for Patient Id");
                return;
            }
        
        
        Patient p = pd.getPatientById(patientID);
        if(p == null){            
            JOptionPane.showMessageDialog(null, "Please select a correct Patient.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  
        }
        AddVitalSignsJPanel avsjp = new AddVitalSignsJPanel(userProcessContainer,p);
        userProcessContainer.add("AddVitalSignsJPanel",avsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);      
    }//GEN-LAST:event_btnViewVitalSignsActionPerformed

    private void btnViewSymptomsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSymptomsActionPerformed
        // TODO add your handling code here:
        int patientID = 0;
        try {
               patientID = Integer.parseInt(txtPatientID.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Please provide correct value "
                        + "for Patient Id");
                return;
            }
        
        
        Patient p = pd.getPatientById(patientID);
        if(p == null){            
            JOptionPane.showMessageDialog(null, "Please select a correct Patient First", "Warning", JOptionPane.WARNING_MESSAGE);
            return;  
        }
        ViewPatientDetailsJPanel vpdjp = new ViewPatientDetailsJPanel(userProcessContainer,p);
        userProcessContainer.add("ViewPatientDetailsJPanel",vpdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewSymptomsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
//        Component[] componentArray = userProcessContainer.getComponents();
//        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchPatient;
    private javax.swing.JButton btnViewSymptoms;
    private javax.swing.JButton btnViewVitalSigns;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblPatientID;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPinCode;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtApartmentNo;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPinCode;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
